# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Citeproc < Formula
  desc ""
  homepage ""
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/citeproc/releases/download/v0.1.6/citeproc_Darwin_x86_64.tar.gz"
      sha256 "739fec6c3ba00d5831ad6ff62268e37c36d81dab0ef697b06c617ee508f457b3"

      def install
        bin.install "citeproc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/citeproc/releases/download/v0.1.6/citeproc_Darwin_arm64.tar.gz"
      sha256 "874ec82055eacea5f4095f69703828db32cb42f13630d3867762778ee7e49a9a"

      def install
        bin.install "citeproc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/citeproc/releases/download/v0.1.6/citeproc_Linux_x86_64.tar.gz"
        sha256 "311c7ac20b8aba55e6d404bfa33442413116e7dc2cb2f2fbbfc779e5f9782681"

        def install
          bin.install "citeproc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/citeproc/releases/download/v0.1.6/citeproc_Linux_arm64.tar.gz"
        sha256 "5596c777e8d5faf9c8f54102489506d953d24fae0dc589d63bcc5ad84eb5276a"

        def install
          bin.install "citeproc"
        end
      end
    end
  end
end
